name: Setup ossutil

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: manyuanrong/setup-ossutil@v2.0
      with:
        endpoint: "oss-cn-shanghai.aliyuncs.com"
        access-key-id: ${{ secrets.ACCESS_KEY_ID }}
        access-key-secret: ${{ secrets.ACCESS_KEY_SECRET }}
        
    - run: ossutil cp ./public oss://wp-hmau/ -r --snapshot-path=test_snapshot # 将xxxxx改为创建的Bucket名称，-rf表示覆盖
